Description: A template for creating EC2 instance with S3 access.

Parameters:
  KeyName:
    Description: Key pair credentials for SSH connection into an EC2 instance
    Type: String
    Default: aws

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

  ImageId:
    Description: The ID of the AMI
    Type: String
    Default: ami-44da5574

  S3BucketName:
    Description: Name of S3 Bucket
    Type: String
    Default: s3_bucket_name

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Ref: ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2IamInstanceProfile
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          /usr/local/bin/aws s3 cp s3://${S3BucketName}/test-file.txt test-file.txt

  EC2IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref S3Role

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource: "*"
      Roles:
        - !Ref S3Role

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access to EC2 instance
      GroupName: !Sub ${AWS::StackName}-SSHSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access to EC2 instance
      GroupName: !Sub ${AWS::StackName}-HTTPSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  PublicIP:
    Description: IP address of created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
