Description: A template for creating EC2 instance.

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

  ImageId:
    Description: The ID of the AMI
    Type: String
    Default: ami-44da5574

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Ref: ImageId

Outputs:
  PublicIP:
    Description: IP address of created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  InstanceID:
    Description: The Instance ID
    Value: !Ref EC2Instance