Description: A template for creating EC2 Auto Scaling Group.

Parameters:
  KeyName:
    Description: Key pair credentials for SSH connection into an EC2 instance
    Type: String
    Default: aws

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

  ImageId:
    Description: The ID of the AMI
    Type: String
    Default: ami-44da5574

  EC2InitScript:
    Description: Script that will be executed on EC2 instance launch
    Type: String
    Default: ""

Resources:
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-EC2LaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroups:
          - !Ref SSHSecurityGroup
          - !Ref HTTPSecurityGroup
        UserData:
          Fn::Base64: !Ref EC2InitScript

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${AWS::StackName}-EC2AutoScalingGroup
      AvailabilityZones:
        Fn::GetAZs: !Ref 'AWS::Region'
      MinSize: '2'
      MaxSize: '2'
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access to EC2 instance
      GroupName: !Sub ${AWS::StackName}-SSHSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access to EC2 instance
      GroupName: !Sub ${AWS::StackName}-HTTPSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SSHSecurityGroupId:
    Description: Id of created SSHSecurityGroup
    Value: !GetAtt SSHSecurityGroup.GroupId

  HTTPSecurityGroupId:
    Description: Id of created HTTPSecurityGroup
    Value: !GetAtt HTTPSecurityGroup.GroupId

  AutoScalingGroupName:
    Description: Name of created Auto Scaling group
    Value: !Ref AutoScalingGroup

  EC2LaunchTemplateLatestVersion:
    Description: The latest version of the EC2 launch template
    Value: !GetAtt EC2LaunchTemplate.LatestVersionNumber